-- Migration 010: Fix orphaned COA accounts for apex-trading
--
-- Problem: During Step 86 live testing, seedDefaultCOA() was called with
-- a UUID tenant_id (39e6bc92e1c5b12334a02e4554bc5a01) generated by
-- PostgresTenantAdapter.createTenant() instead of the real tenant ID
-- 'tenant-apex-trading-003'. The 62 default COA accounts are stranded
-- under the orphaned UUID.
--
-- Fix: UPDATE those 62 rows' tenant_id to the correct value.
-- No account_code collision: orphaned accounts have codes 10000-62202,
-- the only existing account under correct tenant is code 1000.
--
-- Idempotent: WHERE clause targets only the orphaned UUID rows.

-- Verify no collision first (should return 0)
SELECT count(*) AS collision_count
FROM accounts
WHERE tenant_id = 'tenant-apex-trading-003'
  AND account_code IN (
    SELECT account_code FROM accounts
    WHERE tenant_id = '39e6bc92e1c5b12334a02e4554bc5a01'
  );

-- Move orphaned accounts to correct tenant
UPDATE accounts
SET tenant_id = 'tenant-apex-trading-003'
WHERE tenant_id = '39e6bc92e1c5b12334a02e4554bc5a01';

-- Verify result (should be 63: 62 moved + 1 pre-existing)
SELECT count(*) AS total_accounts
FROM accounts
WHERE tenant_id = 'tenant-apex-trading-003';
